### ISSUE TITLE
Begginner question

### ISSUE THREAD

**Issue by alisongonpereira** [freeseek/mochawdl#2]
Hi, and thanks in advance for the help.

I'm very new with wdls and its interactions with docker. I'll tell everything I've run, then my doubts and problems.
I'm running the wdl in a local server, that's got plenty of resources (disk space, RAM, processor). My sample consists on  287 individuals, Illumina GSA array, iScan genotyping.   
I've downloaded the dockerfiles from due section, and built them locally. I've set the input json to my inputs ([mocha_inputs.json](https://github.com/freeseek/mochawdl/files/13860468/mocha_inputs.json)), I've created the tsvs, I've set the image names, and downloaded and extracted the reference files. 

Ok, all set, and the pipeline run with a success stats:

```
[2024-01-07 12:13:14,81] [info] WorkflowManagerActor: Workflow actor for 51934643-1bec-4f38-809b-d2911f4937e6 completed with status 'Succeeded'. The workflow will be removed from the workflow store.
[2024-01-07 12:13:18,20] [info] SingleWorkflowRunnerActor workflow finished with status 'Succeeded'.
```

But some of the results were weird, to say the least. For example, the pileup.pdf is empty. No plots were generated. mocha_stats_tsv shows me genotyped with call_rates of ~0.33, all computed_gender are "U". I've just finished checking other analysis, and unfortunately, those samples were poorly chosen for the test, since those results match the ones I've had running the dragen pipeline to call genotypes. vcf_qc shows an error that all samples were removed during subsetting (And checking a little further, I've seen that's because of low call rate). 

While pipeline was running, I've noticed some feedbacks that goes like this:

```
[2024-01-07 12:12:55,99] [warn] BackendPreparationActor_for_51934643:mocha.mocha_plot:0:1 [51934643]: Docker lookup failed
java.lang.Exception: Unauthorized to get docker hash rggplot2:latest
        at cromwell.engine.workflow.WorkflowDockerLookupActor.cromwell$engine$workflow$WorkflowDockerLookupActor$$handleLookupFailure(WorkflowDockerLookupActor.scala:221)
        at cromwell.engine.workflow.WorkflowDockerLookupActor$$anonfun$3.applyOrElse(WorkflowDockerLookupActor.scala:88)
        at cromwell.engine.workflow.WorkflowDockerLookupActor$$anonfun$3.applyOrElse(WorkflowDockerLookupActor.scala:73)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
        at akka.actor.FSM.processEvent(FSM.scala:707) 

```

Many many times. One thing I want to point out, is that Broad's score 1.17 is currently down, so I've commented out its installation in the docker images, for a test drive of the pipeline. 
There are many many things that can be responsible for the weird results I've got, I know. But in short, I'd like to know:
1) Am I using the dockerfiles, and the docker declaration of the images correct?
2) I've tried sudo usermod -aG docker "my-user", but no success, results still the same.
3) I dont know why the pipeline seems to run, and seems to succeed, even though things dont seem to be calculated. 
4) Is it ok to use score 1.16? It's up by the time I'm writing this.
5) I'm going to try with better samples, and I'll come back here if things work out.

Sorry for the long issue, and the stupidity, I hope to bring good news soon.

**Comment by freeseek** [comment]
When you run a WDL pipeline, you don't need to install software or create docker containers. The required containers with the software will automatically be downloaded when needed. In your case, the workflow finished successfully but all samples were removed from the summary outputs. Notice that even if all samples were removed from the summary outputs, they were still processed by MoChA. However, there clearly must be a problem with the samples if you have such low call rates. You would need to investigate the cause for that first. One possibility is that you mismatched manifest files and IDAT files. Could it be that you provided manifest files for the wrong GSA array version? The pipeline should have generated a couple of files:
```
codigo_240103.green_idat.tsv
codigo_240103.red_idat.tsv
```
What do these files contain in the following columns:
```
number_probes
number_mid_blocks
chip_type
chip_type_guess
```
And what manifest files did you use in the `codigo_240103_batch.tsv` file?

**Comment by alisongonpereira** [comment]
I'm so sorry, I feel pretty stupid. Due to a miscommunication, I've used the wrong references. Indeed, when I corrected that, workflow worked like a charm. Also, I've removed the docker declarations from the input. All right! Thank you for pointing it out!
